config:
  # Whether to enable bStats or not. All submitted data is anonymous.
  # Keeping this enabled helps us (the developers) know if providing
  # support for this plugin is useful for the community, so you may
  # want to keep this enabled. Thanks for using Sentey! :)
  bstats: true

  # Whether to check for plugin updates or not.
  updates:
    # If enabled, this will run an update check on plugin startup.
    plugin-startup: true

    # If enabled, this will register an asynchronous repeating task
    # that will check for updates every 15 minutes.
    repeating-task: true

  # Whether to enable the plugin even if the 'bungeecord' option is
  # disabled on the Spigot configuration files. Not recommended.
  ignore-bungeecord-check: false

  # Whether to enable the plugin even if the server is NOT running
  # Spigot. This is not recommended at all, refrain from enabling it.
  ignore-spigot-check: false

  # List of plugin integrations to enable or disable.
  integrations:
    # Whether to enable the AbuseIPDB integration or not.
    # See: https://abuseipdb.com
    abuseipdb:
      # Whether to automatically send an abuse report to AbuseIPDB or not.
      # Comments can be edited on the "actions" section of each listener (login or server list pings).
      enabled: false

      # The API key used for this integration - get one for free at https://www.abuseipdb.com/account/api
      # Please note that the login actions and ping actions aren't able to use different API keys.
      key: ""

  # Login listener related settings. This can't be disabled entirely since it is the main function of the plugin.
  login:
    # Detects local addresses
    # See: https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#isAnyLocalAddress--)
    block-local-addresses:
      # Whether to enable the check or not
      enabled: false

      # Whether to check for the proxy IP address or not
      check-handshake: false

      # Whether to check the 'spoofed' address or not
      check-spoofed-address: true

    # Detects site local addresses
    # See: https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#isSiteLocalAddress--)
    block-site-local-addresses:
      # Whether to enable the check or not
      enabled: false

      # Whether to check for the proxy IP address or not
      check-handshake: false

      # Whether to check the 'spoofed' address or not
      check-spoofed-address: true

    # Detects loopback addresses
    # See: https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#isLoopbackAddress--)
    block-loopback-addresses:
      # Whether to enable the check or not
      enabled: false

      # Whether to check for the proxy IP address or not
      check-handshake: false

      # Whether to check the 'spoofed' address or not
      check-spoofed-address: true

    # Detects null IP addresses. Since the server is using IP forwarding,
    # BungeeCord (or Velocity) needs to send the player's IP address to
    # the server through a packet. This means that it can be spoofed
    # allowing it to be an invalid IP address - which may cause issues
    # with certain security plugins.
    block-null-addresses:
      # Whether to enable the check or not
      enabled: true

    # Whether to block invalid IP addresses or not. This is usually
    # handled by the "block-null-addresses" detection already.
    block-invalid-addresses:
      # Whether to enable the check or not
      enabled: true

    # Detects the address of a proxy and checks if it's trusted or not.
    # Similar (or almost identical) to the classic "IPWhitelist" plugin.
    unknown-proxies:
      # Whether to enable this detection or not.
      enabled: true

      # Whether to enable unknown proxies' setup mode or not
      # If this is enabled, the unknown proxy detection will be disabled
      # and a message will be displayed to server administrators when
      # they join telling them to set up allowed proxies.
      setup: true

      # The list of allowed proxies
      allowed-proxies: []

    # Actions to take when an unauthorized connection attempt is detected.
    actions:
      abuseipdb:
        # Whether to ignore unauthorized login attempts. Not recommended at all.
        ignore-login: false

        # The comment sent with the report if the AbuseIPDB integration is enabled on the integrations section.
        comment: "Attempted to login to protected Minecraft server on port %serverPort%/tcp (player name: %player%; UUID: %uuid%)"
      disallow-connection:
        # Whether to disallow it or not. Leaving this enabled is recommended.
        enabled: true

        # The message sent to the attacker
        reason: |-
          https://cdn.discordapp.com/attachments/697331954085003314/975608533640953897/mailbox.mov
      commands:
        # Whether to run a list of commands or not
        enabled: false

        # The list of commands to run
        list:
          - "minecraft:ban %player% Unauthorized connection attempt"
          - "minecraft:ban-ip %proxyAddress% Unauthorized connection attempt"
      alerts:
        # Whether to send a message through the chat to online players or not
        enabled: true

        # The message sent to online staff
        message: "&b&lSENTEY >> &fUnauthorized connection attempt made by &c%player%&f. Handshake made from &c%proxyAddress% &7(%detectionType%)"
      webhook:
        # Whether to send a message to a Discord webhook or not
        enabled: false

        # Whether to enable TTS or not. If enabled, the message will be read aloud.
        # Probably annoying, not gonna lie. I don't even know why I'm making this an option.
        tts: false

        # The Discord webhook URL
        url: ""

        # The message that will be sent
        message: "[`%serverAddress%`] | Unauthorized connection attempt from `%player%` (UUID: `%uuid%`; real IP address: `%proxyAddress%`; 'spoofed' IP address: `%address%`; detection type: `%detectionType%`)"

  # Server list ping listener related settings.
  # The server list ping event is normally fired when a player requests the MOTD of the server,
  # but it can also be fired by external programs such as nmap.
  server-list-ping:
    # Whether to enable listening for the server list ping event or not
    enabled: false

    # List of internal filters
    filters:
      # Whether to ignore trusted proxies. 'true' is recommended.
      ignore-trusted-proxies: true

    # The actions taken when a ping is received
    actions:
      alerts:
        # Whether to send a message through the chat to online staff or not
        enabled: true

        # The message sent to online staff
        message: "&b&lSENTEY >> &fServer list ping received from &c%address%&f, is the firewall properly configured?"
      webhook:
        # Whether to send a message to a Discord webhook or not
        enabled: false

        # Whether to enable TTS or not. If enabled, the message will be read aloud.
        # Probably annoying, not gonna lie. I don't even know why I'm making this an option.
        tts: false

        # The Discord webhook URL
        url: ""

        # The message that will be sent
        message: "[`%serverAddress%`] | Server list ping received from `%address%`"
      abuseipdb:
        # Whether to disable auto-reporting on server list pings
        ignore-pings: false

        # The comment sent with the report if the AbuseIPDB integration is enabled on the integrations section.
        comment: "Possible port scan on port %serverPort%/tcp"