name: Sentey
description: Protect your server against common BungeeCord IP forwarding exploits
version: ${project.version}
main: com.comugamers.sentey.Sentey
authors: [ Pabszito, Jojo1545 ]
website: www.comugamers.com
api-version: 1.13

commands:
  sentey:
    description: Main command of the plugin.
    aliases: [ csentey, comusentey ]